# Mod
group=com.chylex.hee
version=2.0.0-dev

# Dependencies
javaVersion=21
minecraftVersion=1.21
parchmentVersion=2024.07.07
neoForgeVersion=21.0.96-beta
kotlinForForgeVersion=5.4.0

# Constraints
minecraftVersionRange=[1.21,)
neoForgeVersionRange=[21.0.96-beta,)
kotlinForForgeVersionRange=[5.4.0,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true
